FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i 's/^# *deb-src/deb-src/' /etc/apt/sources.list
RUN apt-get update && apt-get install -y \
    build-essential fakeroot devscripts quilt dpkg-dev \
    apt-src vim curl
RUN apt-get update && apt-get build-dep -y pam
WORKDIR /build
CMD ["bash"]